### ISSUE TITLE
[BUG] Text is almost invisible in dark mode

### ISSUE THREAD

**Issue by radudum10** [vigo/django-admin-list-filter#10]
## Describe the bug
When using django admin's dark mode, the text color changes (I suppose it gets overwritten by django css) and it gets nearly invisible.

## To Reproduce

I am using DALFRelatedOnlyField with Django 5.0.6. It is a simple FK field.

## Expected behavior
A quick fix would be to change the text color to always be black. A more complex solution is to support themes.

## Screenshots
![image](https://github.com/user-attachments/assets/5d689064-6feb-482e-b88c-5d1767cc0573)

## Environment:
- OS: OpenSUSE Tumbleweed
- CPU: x86_64
- Python version: 3.12
- Django version: 5.0.6
- Django Admin List Filter package version: 0.2.4
- Browser Vendor and version: Mozilla Firefox 129.0

**Comment by vigo** [comment]
Oops, you're right! I never tested this in dark mode. 🙈

**Comment by radudum10** [comment]
Great, thank you!
