### ISSUE TITLE
[Quesion] Can the django-admin-list-filter support CharField/IntegerField？

### ISSUE THREAD

**Issue by zizaihuan** [vigo/django-admin-list-filter#4]
I use DALFRelatedOnlyField in a IntegerField and I get error "NotRelationField at /admin/cmdb/leasedline/"
Is the django-admin-list-filter only support RelateField ?
Can the django-admin-list-filter support CharField/IntegerField？

**Comment by vigo** [comment]
hi, can you please share your model? i'll try to reproduce the issue and fix accordingly

**Comment by vigo** [comment]
hi @zizaihuan , will you provide sample model and code that i can work on it? if not, i'll close to issue :)
